Solvers: Newton polytope pre-processing
iFR-ACSO/casos pull request #35
Opened 2024-01-29 18:55 UTC by renatoloureiro

This PR adds on the grambasis.m a pre-processing method based on the Newton Polytope to reduce the size of the polynomial basis.

2024-01-30 13:04 UTC, tcunis requested changes

2024-01-30 13:04 UTC, tcunis commented on +casos/@PS/grambasis.m
> +% removes monomials outside half Newton polytope
I think we should add an option (Boolean argument) whether or not to run the Newton polytope reduction

2024-01-30 13:47 UTC, renatoloureiro commented on +casos/@PS/grambasis.m
> +% removes monomials outside half Newton polytope
We can check for a field in `opts` structure called 'newton' and verify its value. (either 0/1 or on/off).

2024-08-26 11:46 UTC, tcunis requested changes
Comments must be addressed, then the PR can be merged.

2024-08-26 11:46 UTC, tcunis commented on +casos/+package/+functions/FunctionCommon.m
> +        'newton', 'Monomial basis simplification with Newton polytope (default false).'});
don't add the 'newton' option to class `FunctionCommon` as it only applies to class `SossdpRelaxation` (where its default value is already set). No other class should deal with this option.

2024-08-26 11:46 UTC, tcunis commented on +casos/+package/+solvers/@QuasiconvBisection/buildproblem.m
> +if isfield(opts, 'newton'), sosopt.newton=opts.newton; end
see comment above

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/grambasis.m
> +function [Z,K,z,Mp,Md] = grambasis(S,I,opts)
unless there are more options, we can simply add a binary flag to the `grambasis` method. If we wanted to provide options, we would also need to check those options (cf. class `Options`).

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/grambasis.m
> +% if nargin < 3, useNP=0; end
what is this?

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/grambasis.m
>      idx = find(I);
the third argument needs to be set, too

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +% build LP (part 1)
please provide a description of the LP you (intend) to solve

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +% try to go over each possible monomial basis and verify of it belongs to
"if"

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +% removes monomials outside half Newton polytope
Some more description of this method would be appreciated. Also, function comments should start with a capital letter.

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +    if ~keep(i) && ~dontkeep(i)
Couldn't we iterate over the false-value indices of `keep` only?

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +dontkeep = false(size(keep));
I find these variables' names confusing. In the end, you keep those monomials which are *not* in `dontkeep`...

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/grambasis.m
> +Lz(:,~I) = [];
any particular reason why you've swapped line 74 (prev. 71) for 73 (prev. 72)?

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +            u = find(a'*2*Zdegmat' - b > sqrt(eps));
if I am not mistaken then `Zdegmat` is a logical matrix. In general, it is bad style to do numerical operations with Booleans...

Also, it appears that the first expression is scalar, so why do you need the transpose?

And please write `2*...`

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +        q = Zdegmat(i,:)'*2;
What is the data type of `Zdegmat`? Besides, please write `2*...` instead of `...*2`.

2024-08-26 11:46 UTC, tcunis commented on +casos/@Sparsity/newton_reduce.m
> +    end
if I understand it correctly, the for loop only includes the if statement as main body. To avoid nesting, it would be better to `continue` the for loop if the statement in the if clause does not hold, otherwise just execute the main body.

2024-09-03 14:04 UTC, renatoloureiro commented on +casos/@Sparsity/grambasis.m
> +Lz(:,~I) = [];
No

2024-09-03 14:22 UTC, renatoloureiro commented on +casos/@Sparsity/newton_reduce.m
> +            u = find(a'*2*Zdegmat' - b > sqrt(eps));
The expression is not a scalar but a vector. The scalar b acts on each vector entry generated from `2*Zdegmat*a`.

2024-09-03 15:22 UTC, renatoloureiro commented on +casos/@Sparsity/newton_reduce.m
> +    if ~keep(i) && ~dontkeep(i)
no, since the keep from the trivial removal might have elements that can still be removed by the linear program.

2024-09-03 15:23 UTC, renatoloureiro commented on +casos/@Sparsity/newton_reduce.m
> +dontkeep = false(size(keep));
Fixed. see commit 803b0095b87bfb054cf72446fba4dfc2e6f12c5b

2024-09-04 08:24 UTC, renatoloureiro commented
@tcunis , this PR is ready for its final review.
1. Please check if the option `newton` is passed to the lower interface in the requested way.
2. I added on the function `newton_reduce` the reference to the paper where the algorithm is explained. Does it require a deeper explanation of the algorithm in the `.m` file or should I add it in the documentation (i.e. wiki)?

2024-09-04 10:00 UTC, tcunis approved these changes
Fixed the options for you. Looks good now.

2024-09-04 10:01 UTC, merged