Casos install script
iFR-ACSO/casos pull request #79
Opened 2024-08-09 16:05 UTC by Fabian-Geyer

Added install script that 
- checks if Casos can be used
- tries to add Casos to path if not yet done
- checks for correct Casadi version
- checks which solver is available

and prints the resulting overview in a table to the console.

One small issue remains: In my case when adding CasADi to the matlab path and running the install script again, CasADi does not work immediately. It seems like Matlab always needs a restart to be able to correctly call the toolbox.
This means that users might have to restart Matlab after adding CasADi. )

2024-08-15 15:32 UTC, tcunis reviewed
Overall it looks good, but I am unsure if we should really give a warning if:

- CaΣoS is not on the path yet (that seems to be the default case if the user runs the install script)
- either of the conic solvers is not found (most users won't have all solvers)

Perhaps it suffices to print out some text in either case.

Edit: Tested on Mac w/ M3 processor.

2024-08-15 15:32 UTC, tcunis commented
@JOlucak , @renatoloureiro please check the install script on your machines.

2024-08-15 15:38 UTC, renatoloureiro commented
The install script works as intended on my machine.

2025-05-09 13:34 UTC, JOlucak requested changes
It seems that the script does not work properly. SCS is installed on my computer but the script does not find it. 

- [ ] Check for the SCS issue
- [ ] Add installation/availability of Clarabel solver

We could also think about adding some unit tests here to see if it runs as expected. To be discussed also with Torbjørn.

2025-05-14 08:17 UTC, Fabian-Geyer reviewed
> It seems that the script does not work properly. SCS is installed on my computer but the script does not find it. 
> 
> - [ ] Check for the SCS issue
> - [ ] Add installation/availability of Clarabel solver
> 
> We could also think about adding some unit tests here to see if it runs as expected. To be discussed also with Torbjørn. 

- Can you check if scs is in the Matlab Path while running the script?
- What output do you get when running `>> which scs`?

2025-05-14 09:17 UTC, JOlucak requested changes
Clarabel_mex non existence is correctly found. SCS it seemed something went wrong in startup.m where it should be actually added to the path. Now this issue is also resolved on my side.

I've found some new points that should be clarified.

1. For scs we should also look for the .mex file to make sure it is really installed and ready for use.
2. The current script only checks if things are available. Strictly speaking we are not installing anything. In this case we should rename it to e.g. "check_installation.m" or similar. 
3. If we want to "install" things, at least CaSoS root folder should be automatically added to the matlab path (if not available). 

If we are checking the proper installation, we should definitely add a few basic test functions that check if casos is properly working

2026-01-17 10:35 UTC, tcunis commented
After discussion with @JOlucak, I will close this PR for now. I don't see a real benefit of the install script, since nothing is actually *installed*, but it seems to create more issues. Instead, we will provide guidance on how to install and use CaΣoS with different solvers in the [Wiki](https://github.com/ifr-acso/casos/wiki#getting-started) if not already done.

2026-01-17 10:35 UTC, closed without merging