Bug-fix+enhance: pvolume
iFR-ACSO/casos pull request #88
Opened 2024-09-10 20:36 UTC by renatoloureiro

1. Volume calculation now works for multivariate polynomials.
2. The domain can be given in an arbitrary order of indeterminates: A permutation is performed.

2025-02-13 09:37 UTC, Fabian-Geyer commented
The code works for the example given in the function description.

However, if `casospoly` is a polynomial of type `casos.PS` without symbolic coefficients, the calculation fails. Is this behavior desired?

2025-02-19 19:26 UTC, tcunis commented on +casos/+toolboxes/+sosopt/pvolume.m
>  function [vol,volstd] = pvolume(casospoly,v,domain,npts)
we've never used a variable or parameter named `casospoly` before, please keep parameter names (in particular those being part of the user interface) in line with other methods' interfaces.

2025-02-19 19:27 UTC, tcunis requested changes
Please address Fabian's comment and my comment in file.

2025-02-20 10:34 UTC, renatoloureiro commented on +casos/+toolboxes/+sosopt/pvolume.m
>  function [vol,volstd] = pvolume(casospoly,v,domain,npts)
`function [vol,volstd] = pvolume(p,v,domain,npts)`
Change name of polynomial expression to `p` to follow the description

2025-02-20 11:33 UTC, tcunis commented on +casos/+toolboxes/+sosopt/pvolume.m
> +            'indeterminate variables (or PS, PD).']);
I get what you are trying to do, but it's not the proper way.

1. Please use `is_indets` instead of `isa`; all polynomial-like classes provide this method to check whether an object can be converted to `casos.Indeterminates`.
2. Please use `is_constant`, provided by both `casos.PD` and `casos.PS`, to check whether an object has neither symbolic expressions nor indeterminate variables.
3. Unfortunately, conversion to `casadi.DM` is currently not supported by `casos.PS`. Instead, use conversion to `casos.PD`; the `full` method then returns a double value, provided that `is_constant` is true.
4. Invoking the `full` method in lines 79/80 is unnecessary; by construction, domain must be a polynomial type so `full` is also invoked in lines 85/86.
5. "Vector of indeterminate variables" is the project-wide denomination for a polynomial vector of which all components are single indeterminate variable (with coefficient 1), that is, for a polynomial that can be converted to `casos.Indeterminates`. So, the first column shouldn't be any `PS` or `PD` object but exactly a vector of indeterminate variables.

2025-02-20 19:01 UTC, tcunis approved these changes

2025-02-20 19:01 UTC, merged